version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173' # Expose Vite's default port
    volumes:
      - ./frontend:/app # Mount the local frontend files for hot-reloading
      - /app/node_modules # Avoid issues with overwriting node_modules
    command: bun run host
    environment:
      - CHOKIDAR_USEPOLLING=true # Fix for file watching inside Docker

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000' # Expose port 8000 for the backend API
    volumes:
      - ./backend:/app # Mount local backend files for hot-reloading
      - /app/node_modules # Prevent node_modules issues
    command: bun --hot src/index.ts
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable file watching for hot-reloading

volumes:
  frontend:
  backend: